### ISSUE TITLE
Please implement

### ISSUE THREAD

**Issue by ravi-dhorajiya** [J-Rojas/sudoku-ios#1]
How to set your code UNDO or REDO button to set the value and how can i solve this problem please tell me.

**Comment by J-Rojas** [comment]
You can add this functionality yourself by modifying the View controller with those two buttons and keeping a stack of modified game board positions. When Undo is pressed, you would go back one value in the stack and erase that position of the game board. Redo would move one step forward in the stack to re-apply the value. If the user edits the game board directly, you'll probably want to erase the stack from the current position to the end before adding the next position to the stack.

Feel free to send a pull request if you would like to share the solution here.

**Comment by ravidhorajiya** [comment]
I appreciate sir, but you can implement the code and share the coding in UNDO and REDO button.
